default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: carolinesalib
  host: localhost
  port: 5431

development:
  <<: *default
  database: uberdo3setor_development

test:
  <<: *default
  database: uberdo3setor_test

production:
  <<: *default
  database: <%= ENV['MYAPP_DATABASE_NAME'] %>
  username: <%= ENV['MYAPP_DATABASE_USER'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>
  port: <%= ENV['MYAPP_DATABASE_PORT'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
