default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: postgres
  host: localhost
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *default
  database: boacausa_development

test:
  <<: *default
  database: boacausa_test

