default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: carolinesalib
  host: localhost
  port: 5431

development:
  <<: *default
  database: uberdo3setor_development

test:
  <<: *default
  database: uberdo3setor_test
